name:  Publishing your Storybook to Chromatic

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - '**.js*'
      - '**.ts*'
      - package*.json
      - Dockerfile
      - 'components/**'
      - 'stories/**'
      - 'theme/**'
      - .github/workflows/update-chromatic.yml
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
